name: test comment

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    name: test trigger
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' && contains(github.event.comment.body, 'test')
    steps:
      - name: test
        run: |
          echo "${{ github.event.repository.full_name }}";
          echo "${GITHUB_SHA}";
          echo "${{ github.event }}";